// frontend/components/common/Header.tsx
'use client';
import React from 'react';
import { Disclosure, Menu } from '@headlessui/react';
import { usePathname } from 'next/navigation';
import { auth } from '../../auth';
import Link from 'next/link'; // Import Link from next/link

const navigation: { name: string; href: string }[] = [
  { name: 'Home', href: '/home' },
  { name: 'Dashboard', href: '/dashboard' },
  { name: 'Challenges', href: '/challenges' },
  { name: 'Leaderboard', href: '/leaderboard' },
];

function classNames(...classes: string[]): string {
  return classes.filter(Boolean).join(' ');
}

export const Header = () => {
  const currentPath = usePathname();
  const { data: session } = useSession();

  return (
    <Disclosure as="nav" className="bg-white fixed top-0 w-full z-50 shadow-md">
      <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div className="relative flex h-16 items-center justify-between">
          <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
            {/* Mobile menu button */}
            <Disclosure.Button className="group relative inline-flex items-center justify-center rounded-md p-2 text-charcoal hover:bg-charcoal hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
              <span className="sr-only">Open main menu</span>
              <div className="flex flex-col space-y-1">
                <div className="h-0.5 w-6 bg-charcoal group-hover:bg-white transition duration-200"></div>
                <div className="h-0.5 w-6 bg-charcoal group-hover:bg-white transition duration-200"></div>
                <div className="h-0.5 w-6 bg-charcoal group-hover:bg-white transition duration-200"></div>
              </div>
            </Disclosure.Button>
          </div>
          <div className="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div className="hidden sm:ml-6 sm:block">
              <div className="flex space-x-4">
                {navigation.map((item) => (
                  <Link
                    key={item.name}
                    href={item.href}
                    aria-current={item.href === currentPath ? 'page' : undefined}
                    className={classNames(
                      item.href === currentPath ? 'bg-vibrantCoral text-white font-semibold' : 'text-charcoal hover:bg-vibrantCoral hover:text-white ',
                      'rounded px-3 py-2 text-sm font-regular'
                    )}
                  >
                    {item.name}
                  </Link>
                ))}
              </div>
            </div>
          </div>
          <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            {/* Conditional rendering of Login or Your Profile */}
            {session ? (
              <div className='flex'>
                <Link
                  href="/profile" // Link to user profile page
                  className="text-charcoal hover:bg-vibrantCoral hover:text-white rounded px-3 py-2 text-sm font-semibold"
                >
                  Your Profile
                </Link>
                <Link
                  href=""
                  className=" text-vibrantCoral hover:bg-charcoal hover:text-white rounded px-3 py-2 text-sm font-medium"
                  onClick={() => signOut({ callbackUrl: 'http://localhost:3000/login' })}
                >Logout
                </Link>
              </div>
            ) : (
              <Link
                href="/login" // Use Link for client-side navigation
              >
                <Btn>Login</Btn>


              </Link>
            )}

            {/* Profile dropdown - remove user image */}
            <Menu as="div" className="relative ml-3">
              <Menu.Button className="flex text-sm focus:outline-none focus:ring-2 focus:ring-charcoal focus:ring-offset-2 focus:ring-offset-gray-800">
                <span className="sr-only">Open user menu</span>
                {/* Optional: Add a profile icon or placeholder here */}
              </Menu.Button>
              <Menu.Items
                className="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded bg-vibrantCoral py-1 shadow-lg ring-1 ring-black ring-opacity-5 transition focus:outline-none"
              >
                <Menu.Item>
                  {({ active }: { active: boolean }) => (
                    <a
                      href="#"
                      className={`block px-4 py-2 text-sm text-gray-700 ${active && 'bg-gray-100'}`}
                    >
                      Your Profile
                    </a>
                  )}
                </Menu.Item>
                <Menu.Item>
                  {({ active }: { active: boolean }) => (
                    <a
                      href="#"
                      className={`block px-4 py-2 text-sm text-gray-700 ${active && 'bg-gray-100'}`}
                    >
                      Sign out
                    </a>
                  )}
                </Menu.Item>
              </Menu.Items>
            </Menu>
          </div>
        </div>
      </div>

      <Disclosure.Panel className="sm:hidden">
        <div className="space-y-1 px-2 pb-3 pt-2">
          {navigation.map((item) => (
            <Disclosure.Button
              key={item.name}
              as="a"
              href={item.href}
              aria-current={item.href === currentPath ? 'page' : undefined}
              className={classNames(
                item.href === currentPath ? 'bg-vibrantCoral text-white' : 'text-charcoal hover:bg-vibrantCoral hover:text-white',
                'block rounded px-3 py-2 text-base font-medium'
              )}
            >
              {item.name}
            </Disclosure.Button>
          ))}
        </div>
      </Disclosure.Panel>
    </Disclosure>
  );
};

export default Header;

// frontend-vue/src/components/Header.vue
<template>
  <header class="bg-blue-black text-dark-white shadow-main">
    <nav class="max-w-6xl mx-auto flex items-center justify-between px-4 py-3 gap-4">
      <!-- Logo -->
      <router-link
        to="/"
        class="text-2xl font-bebas-neue tracking-wide hover:text-golden-yellow transition"
      >
        Fantasy Academy
      </router-link>

      <!-- Desktop nav -->
      <ul class="hidden md:flex items-center gap-6 font-alexandria text-sm">
        <li>
          <router-link
            to="/"
            class="hover:text-vibrant-coral transition"
            active-class="text-vibrant-coral font-semibold"
          >
            Home
          </router-link>
        </li>
        <li>
          <router-link
            to="/challenges"
            class="hover:text-vibrant-coral transition"
            active-class="text-vibrant-coral font-semibold"
          >
            Challenges
          </router-link>
        </li>

        <template v-if="!isAuthenticated">
          <li>
            <router-link
              to="/login"
              class="hover:text-vibrant-coral transition"
              active-class="text-vibrant-coral font-semibold"
            >
              Login
            </router-link>
          </li>
          <li>
            <router-link
              to="/signup"
              class="hover:text-vibrant-coral transition"
              active-class="text-vibrant-coral font-semibold"
            >
              Signup
            </router-link>
          </li>
        </template>

        <template v-else>
          <li>
            <router-link
              to="/dashboard"
              class="hover:text-vibrant-coral transition"
              active-class="text-vibrant-coral font-semibold"
            >
              Dashboard
            </router-link>
          </li>
          <li>
            <router-link
              to="/leaderboard"
              class="hover:text-vibrant-coral transition"
              active-class="text-vibrant-coral font-semibold"
            >
              Leaderboard
            </router-link>
          </li>
          <li>
            <router-link
              to="/profile"
              class="hover:text-vibrant-coral transition"
              active-class="text-vibrant-coral font-semibold"
            >
              Profile
            </router-link>
          </li>
          <li>
            <button
              @click="handleLogout"
              class="bg-vibrant-coral px-3 py-1 rounded-lg text-white font-semibold hover:bg-vibrant-coral/80 shadow-sm transition"
            >
              Logout
            </button>
          </li>
        </template>
      </ul>

      <!-- Hamburger (mobile only) -->
      <button
        class="md:hidden inline-flex items-center justify-center rounded-lg p-2 hover:bg-dark-white/10 focus:outline-none focus:ring-2 focus:ring-golden-yellow/60"
        :aria-expanded="mobileOpen.toString()"
        aria-controls="mobile-menu"
        aria-label="Toggle navigation"
        @click="mobileOpen = !mobileOpen"
      >
        <svg v-if="!mobileOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none"
             viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round"
                d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none"
             viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round"
                d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </nav>

    <!-- Mobile panel -->
    <transition enter-active-class="transition duration-150 ease-out"
                enter-from-class="opacity-0 -translate-y-2"
                enter-to-class="opacity-100 translate-y-0"
                leave-active-class="transition duration-100 ease-in"
                leave-from-class="opacity-100 translate-y-0"
                leave-to-class="opacity-0 -translate-y-2">
      <div
        v-if="mobileOpen"
        id="mobile-menu"
        class="md:hidden border-t border-dark-white/10 bg-blue-black/95 backdrop-blur"
      >
        <ul class="flex flex-col gap-1 px-4 py-3 font-alexandria text-sm">
          <li>
            <router-link
              to="/"
              class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
              active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
              @click="closeMobile"
            >
              Home
            </router-link>
          </li>
          <li>
            <router-link
              to="/challenges"
              class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
              active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
              @click="closeMobile"
            >
              Challenges
            </router-link>
          </li>

          <template v-if="!isAuthenticated">
            <li>
              <router-link
                to="/login"
                class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
                active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
                @click="closeMobile"
              >
                Login
              </router-link>
            </li>
            <li>
              <router-link
                to="/signup"
                class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
                active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
                @click="closeMobile"
              >
                Signup
              </router-link>
            </li>
          </template>

          <template v-else>
            <li>
              <router-link
                to="/dashboard"
                class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
                active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
                @click="closeMobile"
              >
                Dashboard
              </router-link>
            </li>
            <li>
              <router-link
                to="/leaderboard"
                class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
                active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
                @click="closeMobile"
              >
                Leaderboard
              </router-link>
            </li>
            <li>
              <router-link
                to="/profile"
                class="block rounded-lg px-3 py-2 hover:bg-dark-white/10 transition"
                active-class="bg-dark-white/10 text-vibrant-coral font-semibold"
                @click="closeMobile"
              >
                Profile
              </router-link>
            </li>
            <li class="pt-1">
              <button
                @click="handleLogout"
                class="w-full text-left rounded-lg bg-vibrant-coral px-3 py-2 font-semibold text-white hover:bg-vibrant-coral/85 shadow-sm transition"
              >
                Logout
              </button>
            </li>
          </template>
        </ul>
      </div>
    </transition>
  </header>
</template>

<script setup>
import { ref, watch } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useAuth } from '@/composables/useAuth';

const { isAuthenticated, logout } = useAuth();
const router = useRouter();
const route = useRoute();

const mobileOpen = ref(false);

function handleLogout() {
  logout();
  mobileOpen.value = false;
  router.push('/login');
}
function closeMobile() {
  mobileOpen.value = false;
}

// zavři menu při změně trasy (když uživatel klikne na link)
watch(
  () => route.fullPath,
  () => { mobileOpen.value = false; }
);
</script>
